spring:
  datasource:
    url: jdbc:postgresql://auth_db:5432/auth_db
    username: postgres
    password: root
        hikari:
      connection-timeout: 20000 
      maximum-pool-size: 10  
  main:
    banner-mode: off
logging:
  level:
    root: warn
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
