spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://auth-db:5433/auth 
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

logging:
  level:
    root: warn
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
