spring:
  application:
    name: gateway-service
  main:
    banner-mode: off
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/**
logging:
  level:
    root: warn
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
