spring:
  application:
    name: gateway-service
  main:
    banner-mode: off
logging:
  level:
    root: warn
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
